threadtest.o: threadtest.cc \
 /home/ugb/ktnaval/kos/src/user/../testoptions.h \
 /home/ugb/ktnaval/kos/src/user/../include/syscalls.h \
 /home/ugb/ktnaval/kos/src/user/../include/kostypes.h \
 /home/ugb/ktnaval/kos/src/user/../include/pthread.h \
 /home/ugb/ktnaval/kos/src/user/../include/syscalls.h
systest.o: systest.cc /home/ugb/ktnaval/kos/src/user/../testoptions.h \
 /home/ugb/ktnaval/kos/src/user/../include/syscalls.h \
 /home/ugb/ktnaval/kos/src/user/../include/kostypes.h
manythread.o: manythread.cc \
 /home/ugb/ktnaval/kos/src/user/../testoptions.h \
 /home/ugb/ktnaval/kos/src/user/../include/syscalls.h \
 /home/ugb/ktnaval/kos/src/user/../include/kostypes.h \
 /home/ugb/ktnaval/kos/src/user/../include/pthread.h \
 /home/ugb/ktnaval/kos/src/user/../include/syscalls.h
kbloop.o: kbloop.cc /home/ugb/ktnaval/kos/src/user/../testoptions.h
